spring.application.name=talentHub

spring.datasource.url=jdbc:postgresql://postgres:5432/talenthub
spring.datasource.username=postgres
spring.datasource.password=91176621

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.docker.compose.enabled=true

security.token.secret=TalentHub@2026#JWT$Secret