# ===========================
# Nome da aplicação
# ===========================
spring.application.name=talentHub

# ===========================
# Banco de Dados
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/talenthub
spring.datasource.username=postgres
spring.datasource.password=91176621

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# Docker
# ===========================
spring.docker.compose.enabled=false